import { useState, useCallback, useMemo, useEffect, useRef } from 'react';
import { Film, Check, Loader, RotateCcw, ArrowLeft } from 'lucide-react';
import { invoke } from '@tauri-apps/api/core';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import { convertFileSrc } from '@tauri-apps/api/core';
import { open } from '@tauri-apps/plugin-dialog';
import { FFmpegDownloadModal } from '../../../Modals';
import { usePhotobooth } from '../../../../contexts';
import { useWorkspaceSettings, usePhotoboothSession, type LastGeneratedMedia } from '../../../../contexts';
import { useUploadQueue } from '../../../../contexts';
import { useAuth } from '../../../../contexts';
import { useToast } from '../../../../contexts';
import { getDriveAuthState, areUploadsEnabled } from '../../../../utils/driveAuthState';
import { createLogger } from '../../../../utils/logger';

const logger = createLogger('GifTabContent');

// Configuration for GIF/Video generation quality settings
const GENERATION_CONFIG = {
  maxDimension: 900,        // Maximum output dimension in pixels
  frameDelayMs: 1000,       // Frame duration in milliseconds
  crf: 10,                  // Constant Rate Factor (lower = better quality)
} as const;

// Separate component for photo grid to defer image loading
function PhotoGrid({
  sessionPhotos,
  selectedPhotos,
  thumbnails,
  isGenerating,
  onTogglePhoto,
}: {
  sessionPhotos: Array<{ filename: string }>;
  selectedPhotos: Set<string>;
  thumbnails: string[];
  isGenerating: boolean;
  onTogglePhoto: (filename: string) => void;
}) {
  return (
    <div className="gif-photo-grid">
      {sessionPhotos.map((photo, index) => {
        const isSelected = selectedPhotos.has(photo.filename);
        // Use pre-generated thumbnail if available, convert asset:// URL
        const rawThumbUrl = thumbnails[index] || '';
        const thumbUrl = rawThumbUrl ? convertFileSrc(rawThumbUrl.replace('asset://', '')) : '';
        return (
          <div
            key={photo.filename}
            className={`gif-photo-item ${isSelected ? 'selected' : ''} ${isGenerating ? 'disabled' : ''}`}
            onClick={() => !isGenerating && onTogglePhoto(photo.filename)}
          >
            {thumbUrl ? (
              <img
                src={thumbUrl}
                alt={photo.filename}
                loading="lazy"
                draggable={false}
              />
            ) : (
              <div className="gif-photo-placeholder" />
            )}
            {isSelected && (
              <div className="gif-photo-check">
                <Check size={14} />
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

export function GifTabContent() {
  const { placedImages, finalizeViewMode } = usePhotobooth();
  const { workingFolder, autoGifEnabled, autoGifFormat, autoGifPhotoSource } = useWorkspaceSettings();
  const { sessions, currentSession, lastGeneratedMedia, setLastGif, setLastVideo, clearLastGenerated } = usePhotoboothSession();
  const { showToast } = useToast();
  const { account } = useAuth();
  const { enqueuePhotos } = useUploadQueue();

  // Compute drive auth state for upload permissions
  const driveAuthState = useMemo(
    () => getDriveAuthState(currentSession?.googleDriveMetadata || null, account),
    [currentSession?.googleDriveMetadata, account]
  );

  // Clear last generated and reset auto-trigger when leaving finalize mode
  useEffect(() => {
    if (finalizeViewMode === 'capture') {
      clearLastGenerated();
      autoGeneratedSessionRef.current = null;
    }
  }, [finalizeViewMode, clearLastGenerated]);


  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState<{ gif: { current: number; total: number; stage: string } | null; video: { current: number; total: number; stage: string } | null }>({
    gif: null,
    video: null,
  });
  const [customMode, setCustomMode] = useState(false);
  const [selectedPhotos, setSelectedPhotos] = useState<Set<string>>(new Set());
  const [outputType, setOutputType] = useState<'both' | 'gif' | 'video'>('both');
  const [showGrid, setShowGrid] = useState(false);
  const [showResult, setShowResult] = useState(false);
const [showFfmpegModal, setShowFfmpegModal] = useState(false);
  const delayRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Track which session was auto-generated to prevent re-triggering
  const autoGeneratedSessionRef = useRef<string | null>(null);
  // Stable ref for handleGenerate so the auto-trigger effect doesn't re-run when it changes
  const handleGenerateRef = useRef<typeof handleGenerate>(null!);

  const sessionFolderName = useMemo(() => {
    const sessionInfo = sessions.find(s => s.id === currentSession?.id);
    return sessionInfo?.folderName || currentSession?.id || '';
  }, [sessions, currentSession]);

  // Photos from current session
  const sessionPhotos = useMemo(() => {
    return currentSession?.photos || [];
  }, [currentSession]);

  // Get thumbnails for the current session from sessions list
  const currentSessionInfo = useMemo(() => {
    return sessions.find(s => s.id === currentSession?.id);
  }, [sessions, currentSession]);

  const sessionThumbnails = useMemo(() => {
    return currentSessionInfo?.thumbnails || [];
  }, [currentSessionInfo]);

  // Extract unique photo paths from the current collage
  const collagePhotoPaths = useMemo(() => {
    const paths: string[] = [];
    placedImages.forEach((img) => {
      if (img.sourceFile && !paths.includes(img.sourceFile)) {
        paths.push(img.sourceFile);
      }
    });
    return paths;
  }, [placedImages]);

  // Extract just the filenames from collage paths for selection
  const collageFilenames = useMemo(() => {
    return collagePhotoPaths.map(path => path.split('/').pop() || path.split('\\').pop() || path);
  }, [collagePhotoPaths]);

  const handleGenerate = useCallback(async (opts?: {
    format?: 'both' | 'gif' | 'video';
    photoSource?: 'collage' | 'all';
    autoUpload?: boolean;
  }) => {
    const format = opts?.format ?? outputType;
    const source = opts?.photoSource;
    const shouldAutoUpload = opts?.autoUpload ?? false;

    // Determine image paths based on source override or current UI state
    let imagePaths: string[];
    if (source === 'all') {
      imagePaths = sessionPhotos.map(p => `${workingFolder}/${sessionFolderName}/${p.filename}`);
    } else if (source === 'collage' || !customMode) {
      imagePaths = collagePhotoPaths;
    } else {
      imagePaths = sessionPhotos
        .filter(p => selectedPhotos.has(p.filename))
        .map(p => `${workingFolder}/${sessionFolderName}/${p.filename}`);
    }

    if (imagePaths.length === 0) {
      showToast('No photos selected', 'warning', 2000);
      return;
    }

    setIsGenerating(true);
    setProgress({ gif: null, video: null });
    clearLastGenerated();

    // Use quality settings from config
    const { maxDimension, frameDelayMs, crf } = GENERATION_CONFIG;

    let unlistenGif: UnlistenFn | null = null;
    let unlistenVideo: UnlistenFn | null = null;

    // Collect generated files for auto-upload
    const generatedFiles: Array<{ filePath: string; fileName: string }> = [];

    try {
      const results: string[] = [];

      if (format === 'both') {
        unlistenGif = await listen<{ current: number; total: number; stage: string }>(
          'gif-generation-progress',
          (event) => setProgress(prev => ({ ...prev, gif: event.payload }))
        );
        unlistenVideo = await listen<{ current: number; total: number; stage: string }>(
          'video-generation-progress',
          (event) => setProgress(prev => ({ ...prev, video: event.payload }))
        );

        const [gifResult, videoResult] = await Promise.all([
          invoke<{ file_path: string; file_size: number }>('generate_gif', {
            imagePaths,
            outputFolder: workingFolder,
            sessionId: sessionFolderName,
            frameDelayMs,
            maxDimension,
          }),
          invoke<{ file_path: string; file_size: number }>('generate_slideshow_video', {
            imagePaths,
            outputFolder: workingFolder,
            sessionId: sessionFolderName,
            frameDelayMs,
            maxDimension,
            loopCount: 1,
            crf,
          }),
        ]);
        results.push(`GIF: ${(gifResult.file_size / 1024).toFixed(0)} KB`, `MP4: ${(videoResult.file_size / 1024).toFixed(0)} KB`);
        const gifFileName = gifResult.file_path.split('/').pop() || gifResult.file_path.split('\\').pop() || 'slideshow.gif';
        const videoFileName = videoResult.file_path.split('/').pop() || videoResult.file_path.split('\\').pop() || 'slideshow.mp4';
        setLastGif({ filePath: gifResult.file_path, fileName: gifFileName, fileSize: gifResult.file_size, photoCount: imagePaths.length });
        setLastVideo({ filePath: videoResult.file_path, fileName: videoFileName, fileSize: videoResult.file_size, photoCount: imagePaths.length });
        generatedFiles.push({ filePath: gifResult.file_path, fileName: gifFileName }, { filePath: videoResult.file_path, fileName: videoFileName });
      } else if (format === 'gif') {
        unlistenGif = await listen<{ current: number; total: number; stage: string }>(
          'gif-generation-progress',
          (event) => setProgress(prev => ({ ...prev, gif: event.payload }))
        );

        const gifResult = await invoke<{ file_path: string; file_size: number }>('generate_gif', {
          imagePaths,
          outputFolder: workingFolder,
          sessionId: sessionFolderName,
          frameDelayMs,
          maxDimension,
        });
        results.push(`GIF: ${(gifResult.file_size / 1024).toFixed(0)} KB`);
        const gifFileName = gifResult.file_path.split('/').pop() || gifResult.file_path.split('\\').pop() || 'slideshow.gif';
        setLastGif({ filePath: gifResult.file_path, fileName: gifFileName, fileSize: gifResult.file_size, photoCount: imagePaths.length });
        generatedFiles.push({ filePath: gifResult.file_path, fileName: gifFileName });
      } else if (format === 'video') {
        unlistenVideo = await listen<{ current: number; total: number; stage: string }>(
          'video-generation-progress',
          (event) => setProgress(prev => ({ ...prev, video: event.payload }))
        );

        const videoResult = await invoke<{ file_path: string; file_size: number }>('generate_slideshow_video', {
          imagePaths,
          outputFolder: workingFolder,
          sessionId: sessionFolderName,
          frameDelayMs,
          maxDimension,
          loopCount: 1,
          crf,
        });
        results.push(`MP4: ${(videoResult.file_size / 1024).toFixed(0)} KB`);
        const videoFileName = videoResult.file_path.split('/').pop() || videoResult.file_path.split('\\').pop() || 'slideshow.mp4';
        setLastVideo({ filePath: videoResult.file_path, fileName: videoFileName, fileSize: videoResult.file_size, photoCount: imagePaths.length });
        generatedFiles.push({ filePath: videoResult.file_path, fileName: videoFileName });
      }

      showToast('Generation complete!', 'success', 3000, results.join(' | '));
      setShowResult(true);

      // Auto-upload generated files to Drive if requested
      if (shouldAutoUpload && generatedFiles.length > 0) {
        const driveFolderId = currentSession?.googleDriveMetadata?.folderId;
        if (currentSession?.id && driveFolderId && areUploadsEnabled(driveAuthState.state)) {
          try {
            const uploadItems = generatedFiles.map(f => ({ filename: f.fileName, localPath: f.filePath }));
            await enqueuePhotos(currentSession.id, uploadItems, driveFolderId);
            logger.debug('[GifTabContent] Auto-uploaded generated media to Drive');
          } catch (uploadErr) {
            logger.error('[GifTabContent] Auto-upload failed:', uploadErr);
          }
        }
      }
    } catch (err) {
      logger.error('[GifTabContent] GIF/Video generation failed:', err);
      const errorMessage = String(err);
      if (errorMessage.includes('FFmpeg not found') || errorMessage.includes('ffmpeg')) {
        setShowFfmpegModal(true);
      } else {
        showToast('Generation failed', 'error', 4000, errorMessage);
      }
    } finally {
      if (unlistenGif) unlistenGif();
      if (unlistenVideo) unlistenVideo();
      setIsGenerating(false);
      setProgress({ gif: null, video: null });
    }
  }, [customMode, selectedPhotos, sessionPhotos, collagePhotoPaths, outputType, workingFolder, sessionFolderName, showToast, setLastGif, setLastVideo, clearLastGenerated, currentSession, driveAuthState, enqueuePhotos]);

  // Keep the ref in sync with latest handleGenerate
  handleGenerateRef.current = handleGenerate;

  // Auto-trigger generation when entering finalize mode
  useEffect(() => {
    logger.debug('[GifTabContent] Auto-trigger effect running:', {
      finalizeViewMode,
      autoGifEnabled,
      sessionId: currentSession?.id,
      workingFolder: !!workingFolder,
      alreadyGenerated: autoGeneratedSessionRef.current,
      willTrigger: finalizeViewMode === 'finalize' && autoGifEnabled && !!currentSession?.id && !!workingFolder && autoGeneratedSessionRef.current !== currentSession?.id,
    });

    if (
      finalizeViewMode === 'finalize' &&
      autoGifEnabled &&
      currentSession?.id &&
      workingFolder &&
      autoGeneratedSessionRef.current !== currentSession.id
    ) {
      // Wait for placedImages to be populated when using collage source
      // (FinalizeView loads image dimensions async before setting placedImages)
      if (autoGifPhotoSource !== 'all' && collagePhotoPaths.length === 0) {
        logger.debug('[GifTabContent] Waiting for collage photos to be placed before auto-generating');
        return;
      }

      // Mark this session as auto-generated to prevent re-triggering
      autoGeneratedSessionRef.current = currentSession.id;

      logger.debug('[GifTabContent] Auto-generating slideshow for session:', currentSession.id, { format: autoGifFormat, source: autoGifPhotoSource });
      const formatLabel = autoGifFormat === 'both' ? 'GIF + MP4' : autoGifFormat === 'gif' ? 'GIF' : 'MP4';
      showToast(`Generating ${formatLabel}...`, 'info', 3000);
      handleGenerateRef.current({
        format: autoGifFormat,
        photoSource: autoGifPhotoSource,
        autoUpload: true,
      });
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [finalizeViewMode, autoGifEnabled, autoGifFormat, autoGifPhotoSource, currentSession?.id, workingFolder, collagePhotoPaths.length]);

  // Download/save media file
  const handleDownload = useCallback(async (filePath: string) => {
    try {
      await open({
        defaultPath: filePath,
        title: 'Save File',
      });
    } catch (err) {
      logger.error('Failed to save file:', err);
    }
  }, []);

  // Upload media to Drive
  const handleUploadToDrive = useCallback(async (filePath: string, fileName: string) => {
    const driveFolderId = currentSession?.googleDriveMetadata?.folderId;
    logger.debug('[GifTabContent] Upload request:', { filePath, fileName, driveFolderId, sessionId: currentSession?.id });

    if (!currentSession?.id) {
      showToast('No active session', 'warning', 3000);
      return;
    }
    if (!driveFolderId) {
      showToast('No Drive folder', 'warning', 3000, 'Please create a Drive folder first');
      return;
    }

    // Check if uploads are enabled (matching account, logged in)
    if (!areUploadsEnabled(driveAuthState.state)) {
      if (driveAuthState.state === 'not_authenticated') {
        showToast('Not signed in', 'warning', 3000, 'Please login to Google Drive');
      } else if (driveAuthState.state === 'authenticated_mismatch') {
        showToast('Account mismatch', 'error', 4000, `Folder created by ${driveAuthState.folderOwner || 'another account'}`);
      }
      return;
    }

    try {
      await enqueuePhotos(
        currentSession.id,
        [{ filename: fileName, localPath: filePath }],
        driveFolderId
      );
      showToast('Upload queued', 'success', 2000);
    } catch (err) {
      logger.error('Failed to upload:', err);
      showToast('Upload failed', 'error', 3000, String(err));
    }
  }, [currentSession, driveAuthState, enqueuePhotos, showToast]);

  // Delay grid rendering for smooth transition
  useEffect(() => {
    if (customMode) {
      setShowGrid(false);
      delayRef.current = setTimeout(() => {
        setShowGrid(true);
      }, 100);
    } else {
      setShowGrid(false);
    }
    return () => {
      if (delayRef.current) {
        clearTimeout(delayRef.current);
      }
    };
  }, [customMode]);

  // Component for displaying a generated media item
  const MediaItem = ({ media, type }: { media: NonNullable<LastGeneratedMedia['gif' | 'video']>, type: 'gif' | 'video' }) => {
    const mediaUrl = convertFileSrc(media.filePath);
    const sizeKB = (media.fileSize / 1024).toFixed(0);
    const videoRef = useRef<HTMLVideoElement>(null);
    const [hasEnded, setHasEnded] = useState(false);
    const [isPlaying, setIsPlaying] = useState(false);

    const handleVideoEnded = () => {
      logger.debug('[Video] Ended');
      setIsPlaying(false);
      setHasEnded(true);
    };

    const handleLoadedData = () => {
      if (videoRef.current && !isPlaying && !hasEnded) {
        logger.debug('[Video] Loaded data, duration:', videoRef.current.duration);
        setIsPlaying(true);
        videoRef.current.play().catch(e => logger.debug('[Video] Play error:', e));
      }
    };

    const handleReplay = () => {
      if (videoRef.current) {
        setHasEnded(false);
        setIsPlaying(true);
        videoRef.current.currentTime = 0;
        videoRef.current.play();
      }
    };

    return (
      <div className="gif-media-item">
        <div className="gif-media-preview-container">
          {type === 'gif' ? (
            <img src={mediaUrl} alt="Generated GIF" className="gif-media-preview" />
          ) : (
            <>
              <video
                ref={videoRef}
                src={mediaUrl}
                className="gif-media-preview"
                muted
                playsInline
                loop={false}
                onEnded={handleVideoEnded}
                onLoadedData={handleLoadedData}
              />
              {hasEnded && (
                <div className="gif-media-replay-overlay" onClick={handleReplay}>
                  <RotateCcw size={24} />
                  <span>Replay</span>
                </div>
              )}
            </>
          )}
        </div>
        <div className="gif-media-info">
          <span className="gif-media-name">{type === 'gif' ? 'slideshow.gif' : 'slideshow.mp4'}</span>
          <span className="gif-media-meta">{sizeKB} KB • {media.photoCount} photos</span>
        </div>
        <div className="gif-media-actions">
          <button
            className="gif-media-btn"
            onClick={() => handleUploadToDrive(media.filePath, media.fileName)}
            title="Upload to Drive"
          >
            Upload
          </button>
          <button
            className="gif-media-btn"
            onClick={() => handleDownload(media.filePath)}
            title="Open in folder"
          >
            Folder
          </button>
        </div>
      </div>
    );
  };

  return (
    <div className="qr-tab-container">
      {showResult && (lastGeneratedMedia?.gif || lastGeneratedMedia?.video) ? (
        <>
          <div className="qr-code-section">
            <div className="qr-code-header" style={{ border: 'none', paddingBottom: '4px' }}>
              <Film size={14} />
              <span className="qr-section-title">Generated</span>
            </div>
          </div>
          <div className="gif-media-list">
            {lastGeneratedMedia.gif && (
              <MediaItem media={lastGeneratedMedia.gif} type="gif" />
            )}
            {lastGeneratedMedia.video && (
              <MediaItem media={lastGeneratedMedia.video} type="video" />
            )}
          </div>
          <button
            className="gif-generate-btn"
            onClick={() => setShowResult(false)}
          >
            <ArrowLeft size={14} />
            <span>Create More</span>
          </button>
        </>
      ) : (
        <>
          {/* Photo Source Section */}
          <div className="qr-code-section">
            <div className="qr-code-header">
              <Film size={14} />
              <span className="qr-section-title">Photos</span>
            </div>

            <div className="gif-segmented-control" data-option-count="2" data-active-index={customMode ? 1 : 0}>
              <div className="slider-track" />
              <div className="gif-segmented-option">
                <button
                  className={!customMode ? 'active' : ''}
                  onClick={() => setCustomMode(false)}
                  disabled={isGenerating}
                >
                  Collage ({collagePhotoPaths.length})
                </button>
              </div>
              <div className="gif-segmented-option">
                <button
                  className={customMode ? 'active' : ''}
                  onClick={() => {
                    if (!customMode) {
                      setCustomMode(true);
                      if (selectedPhotos.size === 0) {
                        setSelectedPhotos(new Set(collageFilenames));
                      }
                    }
                  }}
                  disabled={isGenerating}
                >
                  Custom
                </button>
              </div>
            </div>

            {/* Custom photo selection grid */}
            {customMode && (
              <>
                <div className="gif-selection-label">
                  {selectedPhotos.size} of {sessionPhotos.length} selected
                </div>
                {/* Skeleton while loading */}
                {!showGrid ? (
                  <div className="gif-photo-grid">
                    {Array.from({ length: Math.min(sessionPhotos.length, 12) }).map((_, i) => (
                      <div key={`skeleton-${i}`} className="gif-photo-skeleton" />
                    ))}
                  </div>
                ) : (
                  <PhotoGrid
                    sessionPhotos={sessionPhotos}
                    selectedPhotos={selectedPhotos}
                    thumbnails={sessionThumbnails}
                    isGenerating={isGenerating}
                    onTogglePhoto={(filename) => {
                      if (isGenerating) return;
                      const next = new Set(selectedPhotos);
                      if (next.has(filename)) {
                        next.delete(filename);
                      } else {
                        next.add(filename);
                      }
                      setSelectedPhotos(next);
                    }}
                  />
                )}
              </>
            )}
          </div>

          {/* Output Type Section */}
          <div className="qr-code-section">
            <div className="qr-code-header">
              <Film size={14} />
              <span className="qr-section-title">Output Format</span>
            </div>

            <div className="gif-segmented-control" data-option-count="3" data-active-index={outputType === 'both' ? 0 : outputType === 'gif' ? 1 : 2}>
              <div className="slider-track" />
              <div className="gif-segmented-option">
                <button
                  className={outputType === 'both' ? 'active' : ''}
                  onClick={() => setOutputType('both')}
                  disabled={isGenerating}
                >
                  GIF + MP4
                </button>
              </div>
              <div className="gif-segmented-option">
                <button
                  className={outputType === 'gif' ? 'active' : ''}
                  onClick={() => setOutputType('gif')}
                  disabled={isGenerating}
                >
                  GIF
                </button>
              </div>
              <div className="gif-segmented-option">
                <button
                  className={outputType === 'video' ? 'active' : ''}
                  onClick={() => setOutputType('video')}
                  disabled={isGenerating}
                >
                  MP4
                </button>
              </div>
            </div>
          </div>

          {/* Progress */}
          {isGenerating && (progress.gif || progress.video) && (
            <div className="gif-progress-section">
              <Loader size={14} className="spinning" />
              <div className="gif-progress-bars">
                {progress.gif && (
                  <div className="gif-progress-item">
                    <span className="gif-progress-label">GIF</span>
                    <span className="gif-progress-text">
                      {progress.gif.stage === 'complete'
                        ? 'Done!'
                        : `${progress.gif.stage.charAt(0).toUpperCase() + progress.gif.stage.slice(1)} ${progress.gif.current}/${progress.gif.total}`}
                    </span>
                  </div>
                )}
                {progress.video && (
                  <div className="gif-progress-item">
                    <span className="gif-progress-label">MP4</span>
                    <span className="gif-progress-text">
                      {progress.video.stage === 'complete'
                        ? 'Done!'
                        : `${progress.video.stage.charAt(0).toUpperCase() + progress.video.stage.slice(1)} ${progress.video.current}/${progress.video.total}`}
                    </span>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Generate Button */}
          <button
            className="gif-generate-btn"
            onClick={() => handleGenerate()}
            disabled={
              isGenerating ||
              placedImages.size === 0 ||
              (customMode && selectedPhotos.size === 0)
            }
          >
            {isGenerating ? (
              <>
                <Loader size={14} className="spinning" />
                <span>Generating...</span>
              </>
            ) : (
              <>
      {/* FFmpeg Download Modal */}
      {showFfmpegModal && (
        <FFmpegDownloadModal
          show={showFfmpegModal}
          onClose={() => setShowFfmpegModal(false)}
          onDownloadComplete={() => {
            setShowFfmpegModal(false);
            // Optionally retry the generation
          }}
        />
      )}
                <Film size={14} />
                <span>Generate Slideshow</span>
              </>
            )}
          </button>
        </>
      )}
    </div>
  );
}
